`define INOP		4'H0
`define IHALT       4'H1
`define IRRMOVL     4'H2
`define IIRMOVL     4'H3
`define IRMMOVL     4'H4
`define IMRMOVL     4'H5
`define IOPL        4'H6
`define IJXX        4'H7
`define ICALL       4'H8
`define IRET        4'H9
`define IPUSHL      4'HA
`define IPOPL       4'HB
`define FNONE       4'H0
`define RESP        4'H4
`define RNONE       4'HF
`define ALUADD      4'H0
`define SAOK        4'H1
`define SADR        4'H2
`define SINS        4'H3
`define SHLT        4'H4
